name: Hourly MP3 Update to GitHub Pages

on:
  schedule:
    - cron: '3 * * * *'  # 毎時間3分に実行
  workflow_dispatch:     # 手動実行も可能

jobs:
  update-github-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # リポジトリへの書き込み権限を付与

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 完全な履歴を取得

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mutagen

      - name: Run MP3 to GitHub Pages script
        run: python mp3_to_github_pages.py

      - name: Check for changes
        id: git-check
        run: |
          git add docs/
          git status
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push to gh-pages branch
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -m "Update podcast files and GitHub Pages [skip ci]"
          
          # gh-pagesブランチが存在するか確認
          if git ls-remote --heads origin gh-pages | grep -q 'gh-pages'; then
            # gh-pagesブランチが存在する場合、そのブランチを更新
            git push origin HEAD:gh-pages
          else
            # gh-pagesブランチが存在しない場合、新規作成
            git checkout -b gh-pages
            git push -u origin gh-pages
          fi
