name: Hourly MP3 Update to GitHub Pages

on:
  schedule:
    - cron: '3 * * * *'  # 毎時間3分に実行
  workflow_dispatch:     # 手動実行も可能

jobs:
  update-github-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # リポジトリへの書き込み権限を付与

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 完全な履歴を取得

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mutagen

      - name: Ensure podcast directory exists
        run: |
          mkdir -p docs/podcast
          touch docs/podcast/.gitkeep
          echo "Created or confirmed docs/podcast directory"

      - name: Run MP3 to GitHub Pages script
        run: python mp3_to_github_pages.py

      - name: Debug directory structure
        run: |
          echo "Current directory structure:"
          find docs -type f | sort
          echo "Total files in docs/podcast: $(find docs/podcast -type f | wc -l)"

      - name: Check for changes
        id: git-check
        run: |
          # 変更をステージングエリアに追加
          git add docs/
          git status
          
          # 変更があるかどうかを確認
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -m "Update podcast files and GitHub Pages [skip ci]"
          
          # mainブランチにコミットしてプッシュ
          git push origin HEAD:main
          
          # gh-pagesブランチが存在するか確認し、変更を反映
          if git ls-remote --heads origin gh-pages | grep -q 'gh-pages'; then
            echo "Updating existing gh-pages branch"
            git checkout gh-pages
            git pull origin gh-pages
            git checkout main docs/
            git add docs/
            git commit -m "Update gh-pages with latest podcast files [skip ci]" || echo "No changes to commit"
            git push origin gh-pages
          else
            echo "Creating new gh-pages branch"
            git checkout -b gh-pages
            git push -u origin gh-pages
          fi

      - name: Check results
        run: |
          echo "Workflow completed. Check the repository to verify changes."
          echo "Main branch should have latest changes."
          echo "Gh-pages branch should reflect the same changes in docs/ directory."
