name: Podcast RSS Generator

on:
  schedule:
    - cron: '3 * * * *'  # 毎時間3分に実行
  workflow_dispatch:  # 手動実行用
  push:
    paths:
      - 'docs/podcast/**'  # podcast フォルダに変更があった場合に実行

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedgen requests
          
      - name: Generate RSS feed
        run: python .github/scripts/generate_podcast_rss.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs/podcast.xml
          git diff --staged --quiet || (git commit -m "自動更新: podcast RSS feed" && git push)
