name: Update Spotify RSS Feed

on:
  schedule:
    - cron: '3 * * * *'  # 毎時間3分に実行
  workflow_dispatch:     # 手動実行も可能

jobs:
  update-rss:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # リポジトリコンテンツの書き込み権限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mutagen

      - name: Update RSS feed
        run: python update_rss.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add podcast.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update podcast RSS feed - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
